"""job_runs erro (motivo da falha)

Revision ID: 7f668fb682d4
Revises: 915d234f47ca
Create Date: 2026-09-05 12:53:34.246860

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f668fb682d4"
down_revision: str | Sequence[str] | None = "915d234f47ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job_runs", sa.Column("error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_runs", "error")
    # ### end Alembic commands ###
