"""mpls models

Revision ID: 9081b87de351
Revises: c0ef353917c5
Create Date: 2026-09-07 10:40:02.875508

"""
from collections.abc import Sequence

import sqlalchemy as sa


from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9081b87de351'
down_revision: str | Sequence[str] | None = 'c0ef353917c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpls_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('admin_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('l2vc_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('vc_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('mtu', sa.Integer(), nullable=False),
    sa.Column('control_word', sa.Boolean(), nullable=False),
    sa.Column('flow_label', sa.Boolean(), nullable=False),
    sa.Column('redundancy', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('admin_status', sa.Boolean(), nullable=False),
    sa.Column('operational_status', sa.Enum('unknown', 'up', 'down', 'partial', name='mpls_oper_status'), nullable=False),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['mpls_domains.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'name'),
    sa.UniqueConstraint('domain_id', 'vc_id')
    )
    op.create_table('vsi_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('vsi_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('vrp_name', sa.String(length=64), nullable=False),
    sa.Column('signaling', sa.Enum('ldp', name='service_signaling'), nullable=False),
    sa.Column('mtu', sa.Integer(), nullable=False),
    sa.Column('split_horizon', sa.Boolean(), nullable=False),
    sa.Column('mac_learning', sa.Boolean(), nullable=False),
    sa.Column('mac_limit', sa.Integer(), nullable=True),
    sa.Column('admin_status', sa.Boolean(), nullable=False),
    sa.Column('operational_status', sa.Enum('unknown', 'up', 'down', 'partial', name='mpls_oper_status'), nullable=False),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['mpls_domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'vrp_name'),
    sa.UniqueConstraint('domain_id', 'vsi_id')
    )
    op.create_table('mpls_domain_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('loopback_address', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('pe', 'core', name='mpls_role'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['mpls_domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'device_id')
    )
    op.create_table('vsi_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vsi_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['vsi_id'], ['vsi_services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vsi_id', 'device_id')
    )
    op.create_table('service_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('l2vc', 'vsi', name='service_kind'), nullable=False),
    sa.Column('l2vc_id', sa.Integer(), nullable=True),
    sa.Column('vsi_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('interface', sa.String(length=64), nullable=False),
    sa.Column('encapsulation', sa.Enum('dot1q', 'qinq', 'ethernet_raw', name='service_encap'), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('inner_vlan', sa.Integer(), nullable=True),
    sa.Column('mtu', sa.Integer(), nullable=True),
    sa.Column('operational_status', sa.Enum('unknown', 'up', 'down', 'partial', name='mpls_oper_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['l2vc_id'], ['l2vc_services.id'], ),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlans.id'], ),
    sa.ForeignKeyConstraint(['vsi_id'], ['vsi_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("ALTER TYPE vlan_kind ADD VALUE IF NOT EXISTS 'mpls_ac'")
    op.add_column('devices', sa.Column('capabilities', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False))
    op.add_column('vlans', sa.Column('device_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('vlans_site_id_vid_key'), 'vlans', type_='unique')
    op.create_index('uq_vlans_device_vid', 'vlans', ['device_id', 'vid'], unique=True, postgresql_where=sa.text('device_id IS NOT NULL'))
    op.create_index('uq_vlans_site_vid', 'vlans', ['site_id', 'vid'], unique=True, postgresql_where=sa.text('device_id IS NULL'))
    op.create_foreign_key('vlans_device_id_fkey', 'vlans', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vlans_device_id_fkey', 'vlans', type_='foreignkey')
    op.drop_index('uq_vlans_site_vid', table_name='vlans', postgresql_where=sa.text('device_id IS NULL'))
    op.drop_index('uq_vlans_device_vid', table_name='vlans', postgresql_where=sa.text('device_id IS NOT NULL'))
    op.create_unique_constraint(op.f('vlans_site_id_vid_key'), 'vlans', ['site_id', 'vid'], postgresql_nulls_not_distinct=False)
    op.drop_column('vlans', 'device_id')
    op.drop_column('devices', 'capabilities')
    op.drop_table('service_endpoints')
    op.drop_table('vsi_members')
    op.drop_table('mpls_domain_members')
    op.drop_table('vsi_services')
    op.drop_table('l2vc_services')
    op.drop_table('mpls_domains')
    # ### end Alembic commands ###
