"""fluxo de mudança: change_requests, change_steps, approvals (ciclo D, spec §4)

Revision ID: c0ef353917c5
Revises: 7f668fb682d4
Create Date: 2026-09-05 18:12:02.974169

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0ef353917c5"
down_revision: str | Sequence[str] | None = "7f668fb682d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.Enum('provision', 'remove', name='change_action'), nullable=False),
    sa.Column('criticidade', sa.Enum('baixa', 'media', 'alta', name='change_criticality'), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('ticket', sa.String(length=64), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('rascunho', 'aguardando_aprovacao', 'aprovado', 'executando', 'aplicado', 'com_divergencia', 'parcial', 'erro', 'rejeitado', 'cancelado', name='change_status'), nullable=False),
    sa.Column('rollback_de', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['rollback_de'], ['change_requests.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('decisao', sa.Enum('aprovar', 'rejeitar', name='approval_decision'), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_request_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aplicado', 'pulado', 'falhou', 'rollback', name='change_step_status'), nullable=False),
    sa.Column('plano_json', sa.JSON(), nullable=False),
    sa.Column('aviso', sa.Text(), nullable=True),
    sa.Column('baseline_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('backup_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('post_check_json', sa.JSON(), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['backup_snapshot_id'], ['device_snapshots.id'], ),
    sa.ForeignKeyConstraint(['baseline_snapshot_id'], ['device_snapshots.id'], ),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_steps')
    op.drop_table('approvals')
    op.drop_table('change_requests')
    # ### end Alembic commands ###
